---
# Workloads
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  namespace: kube-system
  name: snapshot-controller
spec:
  interval: 5m
  url: https://github.com/kubernetes-csi/external-snapshotter
  ref:
    tag: v8.1.0
  ignore: |
    /*
    # include the manifest folder
    !/deploy/kubernetes/snapshot-controller
