# yaml-language-server: $schema=https://www.schemastore.org/github-issue-forms.json
name: Kubernetes upgrade
title: Upgrade Kubernetes to {{1.32}}
description: Kubernetes upgrade template
body:
  - type: textarea
    attributes:
      label: Description
      value: |
        Kubernetes upgrade note.

        [x] Related PR(s):
          - #pr-number

        [x] Related Issue(s):
          - #issue-number

        ## Kubernetes {{1.32}}
        https://kubernetes.io/blog/{{2024/12/11/kubernetes-v1-32-release}}/

        ### Features
        #### to Stable:

        - feature-s1

        #### to Beta

        - feature-b1

        #### to Alpha

        - feature-a1

        ### Deprecated

        - drop-d1

        ## Upgrade process
        - [ ] 1. Backup etcd. Trigger the backup workflow:
        ```
        task kubernetes:etcd-backup:backup
        ```

        - [ ] 2. Merge the PR, and Tuppr will handle the upgrade process

        - [ ] 3. Check the upgrade result
