# yaml-language-server: $schema=https://www.schemastore.org/github-issue-forms.json
name: Talos upgrade
title: Upgrade Talos to {{v1.11}}
description: Talos upgrade template
body:
  - type: textarea
    attributes:
      label: Description
      value: |
        Talos upgrade note.

        Related PR(s):
        - #pr-number

        ## Talos {{v1.11}}
        Release doc: https://docs.siderolabs.com/talos/{{v1.11}}/getting-started/what's-new-in-talos

        Support Kubernetes {{1.29}} - {{1.34}}
        Core components default version:
        - CoreDNS: {{1.12.2}}
        - etcd: {{3.6.4}}

        ### Features
        - feature-1

        ### Deprecated
        - drop-d1

        ### Upgrade process
        - [ ] 1. Backup etcd. Trigger the backup workflow:
        ```
        task kubernetes:etcd-backup:backup
        ```

        - [ ] 2. Merge the PR, and Tuppr will handle the upgrade process

        - [ ] 3. Check the upgrade result
