# yaml-language-server: $schema=https://www.schemastore.org/github-issue-forms.json
name: Talos upgrade
title: Upgrade Talos to {{v1.11}}
description: Talos upgrade template
body:
  - type: textarea
    attributes:
      label: Description
      value: |
        Talos upgrade note.

        - [x] Related PR(s):
          - #pr-number
        - [x] Related Issue(s):
          - #issue-number

        ## Talos {{v1.11}}
        Support Kubernetes {{1.29}}-{{1.34}}

        ### Features
        - feature-1

        ### Deprecated
        - drop-d1

        ## Upgrade process
        ### Pre-upgrade tasks
        - [ ] Check Kubernetes cluster health
          ```bash
          talosctl health
          ```
        - [ ] Backup etcd
          ```bash
          task kubernetes:etcd-backup:backup
          ```

        ### Upgrade execution
        - [ ] Login to secrert provider
          ```bash
          aws sso login
          ```
        - [ ] Upgrade control plane(s) first
          ```bash
          task talos:plan-nuc12wshi5-1
          task talos:upgrade-nuc12wshi5-1
          ```
        - [ ] Upgrade worker(s)
          ```bash
          task talos:plan-nuc11tnhi50l-1
          task talos:upgrade-nuc11tnhi50l-1
          # continue to other workers
          ```

        ### Post-upgrade verification
        - [ ] Check Kubernetes cluster health again
          ```bash
          talosctl health
          ```

        ## References
        https://docs.siderolabs.com/talos/{{v1.11}}/overview/what-is-talos
