---
# yaml-language-server: $schema=https://www.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - base/ns.yaml
  - app/release.yaml
  - issuer/rbac.yaml
  - issuer/timtor-dev-clusterissuer.yaml
  - issuer/timtor-dev-clusterissuer-secret.yaml
