{
 "title": "Home",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "promsource", "label": "prom source", "query": "prometheus" },
   { "name": "lokisource", "label": "loki source", "query": "loki" },
   {
    "name": "node",
    "label": "node",
    "query": {
     "query": "label_values(node_uname_info, nodename)"
    }
   },
   {
    "name": "minstep",
    "label": "min step",
    "query": "30s,1m,10m,30m,1h,6h,12h,1d,7d,"
   }
  ]
 },
 "panels": [
  { "title": "Node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Summary",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "label_replace(node_uname_info, \"ip\", \"$1\", \"instance\" , \"(.*):.*\" )"
    },
    { "expr": "instance:node_num_cpu:sum" },
    { "expr": "node_memory_MemTotal_bytes" },
    {
     "expr": "time() - node_boot_time_seconds"
    },
    {
     "expr": "avg(node_hwmon_temp_celsius) by (instance)"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(1 -(avg by (instance) (irate(node_cpu_seconds_total{mode=~\"idle\"} [$__rate_interval]))))\n*100\n*on(instance) group_left(nodename) node_uname_info\n{nodename=~\"$node\"}",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg by (instance) (1-(node_memory_MemAvailable_bytes/node_memory_MemTotal_bytes))\n* 100\n* on(instance) group_left(nodename) node_uname_info\n{nodename=~\"$node\"}",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  {
   "title": "Temperatue",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "avg (node_hwmon_temp_celsius) by (instance)\n* on(instance) group_left(nodename) node_uname_info\n{nodename=~\"$node\"}",
     "legendFormat": "{{ nodename }}"
    }
   ]
  },
  {
   "title": "Disk usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(\n(1- (node_filesystem_avail_bytes/node_filesystem_size_bytes{mountpoint=\"/\"}))\n*100\n* on(instance) group_left(nodename) node_uname_info\n{nodename=~\"$node\"})",
     "legendFormat": "{{nodename}}"
    },
    {}
   ]
  },
  { "title": "Cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "PVC usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 13, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - \navg(kubelet_volume_stats_available_bytes{job=\"kubelet\"}/kubelet_volume_stats_capacity_bytes) \nby (persistentvolumeclaim)",
     "legendFormat": "{{persistentvolumeclaim}}"
    }
   ]
  }
 ]
}