---
# yaml-language-server: $schema=https://www.schemastore.org/github-workflow.json
name: flux-local

on:
  pull_request:

jobs:
  lint:
    name: Flux local
    runs-on: ubuntu-latest
    strategy:
      matrix:
        resource: ["helmrelease", "kustomization"]
    steps:
      - name: Setup Flux CLI
        uses: fluxcd/flux2/action@04acaec6161ac4fb1a82ffafa88901c03271d34f # v2.8.6
      - uses: allenporter/flux-local/action/diff@4d666add25002f550dc0dbe8b2b2f25859169b34 # 8.2.0
        id: diff
        with:
          path: kubernetes/flux-system
          sources: homelab
          resource: ${{ matrix.resource }}
      - name: PR Comments
        uses: mshick/add-pr-comment@8e4927817251f1ff60c001f04568532b38e0b4a0 # v3.11
        if: ${{ steps.diff.outputs.diff != '' }}
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          message-id: "${{ github.event.pull_request.number }}/${{ matrix.resource }}"
          message-failure: flux-local diff is not successful
          message: |
            `````diff
            ${{ steps.diff.outputs.diff }}
            `````
