---
# yaml-language-server: $schema=https://www.schemastore.org/github-workflow.json
name: flux-local

on:
  pull_request:

jobs:
  lint:
    name: Flux local
    runs-on: ubuntu-latest
    strategy:
      matrix:
        resource: ["helmrelease", "kustomization"]
    steps:
      - name: Setup Flux CLI
        uses: fluxcd/flux2/action@dcc7def046cba2fe8d15d9737a4c250100f62fe0 # v2.9.0
      - uses: allenporter/flux-local/action/diff@92d3a538c009c3fec120fbf50f6ef33b3e0a569c # 8.4.0
        id: diff
        with:
          path: kubernetes/flux-system
          sources: homelab
          resource: ${{ matrix.resource }}
      - name: PR Comments
        uses: mshick/add-pr-comment@ec328af66588ab8f77cdeb2c264f14aba45bbf59 # v3.12
        if: ${{ steps.diff.outputs.diff != '' }}
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          message-id: "${{ github.event.pull_request.number }}/${{ matrix.resource }}"
          message-failure: flux-local diff is not successful
          message: |
            `````diff
            ${{ steps.diff.outputs.diff }}
            `````
