---
# yaml-language-server: $schema=https://www.schemastore.org/github-workflow.json
name: format-check

on:
  pull_request:

jobs:
  lint:
    name: Format check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: dprint/check@7dc032d8874778fc024f6f9b4a7e6d896782c330 # v2.5
