---
# yaml-language-server: $schema=https://www.schemastore.org/github-workflow.json
name: yaml-schema-check

on:
  pull_request:

jobs:
  check:
    name: Yaml schema check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - run: npx --yes yaml-ls-check@1.4 ./
