---
# yaml-language-server: $schema=https://www.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - app/repo.yaml
  - app/release.yaml
  - app/gatewayclass.yaml
  - app/netpol.yaml
  - bgp/bgpadvertisement.yaml
  - bgp/bgpclusterconfig.yaml
  - bgp/bgppeerconfig.yaml
  - loadbalancer/ippool.yaml
  - loadbalancer/certificate.yaml
  - loadbalancer/gateway.yaml
