---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/cilium.io/ciliumloadbalancerippool_v2alpha1.json
apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: "default-pool"
spec:
  blocks:
    - cidr: "192.168.252.1/32"
  serviceSelector:
    matchLabels:
      io.cilium.gateway/owning-gateway: cilium-default
      gateway.networking.k8s.io/gateway-name: cilium-default
